redirectsOrigin = "config"
plugins = []
headers = []

[build]
edge_functions = "E:\\桌面\\工作集合表\\netlify\\edge-functions"
publish = "E:\\桌面\\工作集合表\\dist"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[edge_functions]]
path = "/api/jobs"
function = "jobs-api"

[[edge_functions]]
path = "/api/jobs/stats"
function = "jobs-api"

[[edge_functions]]
path = "/api/kimi/*"
function = "cors-proxy"

[[edge_functions]]
path = "/api/moonshot/*"
function = "cors-proxy"

[[edge_functions]]
path = "/api/coze/*"
function = "cors-proxy"

[functions]

[functions."*"]

[[redirects]]
from = "/api/kimi/*"
to = "https://api.kimi.com/coding/v1/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]
X-From = "netlify-proxy"

[[redirects]]
from = "/api/moonshot/*"
to = "https://api.moonshot.ai/v1/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/coze/*"
to = "https://api.coze.cn/v3/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/job_dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]