redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/harry/Desktop/工作集合表"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/kimi/*"
to = "https://api.kimi.com/coding/v1/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]
X-From = "netlify-proxy"

[[redirects]]
from = "/api/coze/*"
to = "https://api.coze.cn/v3/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/job_dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]